# Generated by Django 6.1 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'Customer Support'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales Executive'), ('purchase', 'Purchase Team'), ('accounts', 'Accounts'), ('support', 'Customer Support'), ('hr_manager', 'HR Manager')], default='sales_executive', max_length=20),
        ),
    ]
