# Generated by Django 6.1 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales Executive'), ('purchase', 'Purchase Team'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('it_lead', 'IT Lead'), ('developer', 'Developer'), ('hr_manager', 'HR Manager')], default='sales_executive', max_length=20),
        ),
    ]
