# Generated by Django 6.1 on 2026-08-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_support_into_it_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales'), ('purchase', 'Purchase Team'), ('accounts', 'Accounts'), ('it_lead', 'IT Lead'), ('developer', 'Developer'), ('warehouse_manager', 'Warehouse Manager'), ('warehouse', 'Warehouse Team'), ('hr_manager', 'HR Manager')], default='sales_executive', max_length=20),
        ),
    ]
