# Generated by Django 6.1 on 2026-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales'), ('purchase', 'Purchase Team'), ('accounts', 'Accounts'), ('it_lead', 'IT Lead'), ('developer', 'Developer'), ('warehouse_manager', 'Warehouse Manager'), ('warehouse', 'Warehouse Team'), ('rider', 'Rider'), ('hr_manager', 'HR Manager')], default='sales_executive', max_length=20),
        ),
    ]
