# Generated by Django 6.1 on 2026-08-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0009_task_actual_minutes_task_progress_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'Customer Support'), ('hr', 'Human Resources'), ('management', 'Management')], max_length=20)),
                ('category', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('classification', models.CharField(blank=True, choices=[('human', 'Human Mistake'), ('process', 'Process/SOP Failure'), ('system', 'Software/System Failure'), ('management', 'Management/Training Failure'), ('external', 'External Failure')], max_length=12)),
                ('description', models.TextField(max_length=3000)),
                ('impact', models.CharField(blank=True, default='', max_length=500)),
                ('financial_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occurrence_level', models.PositiveSmallIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, default='', max_length=2000)),
                ('root_cause', models.CharField(blank=True, choices=[('lack_of_training', 'Lack of training'), ('lack_of_attention', 'Lack of attention'), ('sop_not_followed', 'SOP not followed'), ('sop_missing', 'SOP missing'), ('sop_unclear', 'SOP unclear'), ('wrong_information', 'Wrong information provided'), ('communication_failure', 'Communication failure'), ('system_issue', 'System issue'), ('data_issue', 'Data issue'), ('workload_issue', 'Workload issue'), ('time_pressure', 'Time pressure'), ('approval_failure', 'Approval failure'), ('human_error', 'Human error'), ('managerial_failure', 'Managerial failure'), ('vendor_issue', 'Vendor issue'), ('customer_issue', 'Customer issue'), ('other', 'Other')], max_length=25)),
                ('root_cause_note', models.CharField(blank=True, default='', max_length=500)),
                ('corrective_action', models.TextField(blank=True, default='', max_length=1000)),
                ('preventive_action', models.TextField(blank=True, default='', max_length=1000)),
                ('sop_name', models.CharField(blank=True, default='', max_length=150)),
                ('sop_version', models.CharField(blank=True, default='', max_length=40)),
                ('sop_step', models.CharField(blank=True, default='', max_length=200)),
                ('sop_followed', models.BooleanField(blank=True, null=True)),
                ('sop_adequate', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('explained', 'Explained'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('manager_remarks', models.CharField(blank=True, default='', max_length=1000)),
                ('level3_action', models.CharField(blank=True, choices=[('coaching', 'Coaching'), ('retraining', 'Retraining'), ('written_warning', 'Written warning'), ('pip', 'Performance Improvement Plan'), ('role_reassignment', 'Role reassignment'), ('additional_approval', 'Additional approval requirement'), ('process_change', 'Process change'), ('permission_suspension', 'Suspension of certain permissions'), ('other', 'Other HR-approved action')], max_length=25)),
                ('level3_action_note', models.CharField(blank=True, default='', max_length=500)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrective_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_corrective', to='crm.task')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='crm.lead')),
                ('manager', models.ForeignKey(blank=True, help_text='Accountable for the correction (reporting manager at log time).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_mistakes', to=settings.AUTH_USER_MODEL)),
                ('repeat_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats', to='mistakes.mistake')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_mistakes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The task where it happened.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes_here', to='crm.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mistake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mistakes.mistake')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_low_hours', models.PositiveIntegerField(default=72)),
                ('sla_medium_hours', models.PositiveIntegerField(default=48)),
                ('sla_high_hours', models.PositiveIntegerField(default=24)),
                ('sla_critical_hours', models.PositiveIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mistake categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_mistake_category')],
            },
        ),
    ]
