# Generated by Django 6.1 on 2026-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakesettings',
            name='last_daily_digest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mistakesettings',
            name='last_weekly_digest',
            field=models.DateField(blank=True, null=True),
        ),
    ]
