# Generated by Django 6.1 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0003_mistakesettings_last_daily_digest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], max_length=20),
        ),
    ]
