# Generated by Django 6.1 on 2026-09-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0004_alter_mistake_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], max_length=20),
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', help_text="Matches the mistake category, e.g. 'Data Entry'.", max_length=60)),
                ('version', models.CharField(default='v1', max_length=40)),
                ('steps', models.TextField(help_text="One step per line, in order. Say exactly what to do and what 'done correctly' looks like.")),
                ('checks', models.TextField(blank=True, default='', help_text='What to verify before calling it done.')),
                ('common_errors', models.TextField(blank=True, default='', help_text='Mistakes people actually make here — this is what the AI matches a new mistake against.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_sops', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Who keeps this process up to date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
                'ordering': ['department', 'title', '-version'],
            },
        ),
        migrations.AddField(
            model_name='mistake',
            name='sop',
            field=models.ForeignKey(blank=True, help_text='The written process this was judged against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='mistakes.sop'),
        ),
        migrations.AddConstraint(
            model_name='sop',
            constraint=models.UniqueConstraint(fields=('title', 'version'), name='uniq_sop_version'),
        ),
    ]
