# Generated by Django 6.1 on 2026-09-05 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('template', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='accepted', max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp deliveries',
                'ordering': ['-sent_at'],
            },
        ),
    ]
