# Generated by Django 6.1 on 2026-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='lead_department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'Customer Support'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
    ]
