# Generated by Django 6.1 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webforms', '0002_alter_form_lead_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='lead_department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
    ]
