# Generated by Django 6.1 on 2026-08-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_assignmentrule_lead_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('gmail', 'Gmail')], max_length=10)),
                ('external_id', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('media', models.JSONField(blank=True, default=list)),
                ('ai_result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='uniq_channel_external_id')],
            },
        ),
    ]
