# Generated by Django 6.1 on 2026-08-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'Customer Support'), ('management', 'Management')], max_length=20, unique=True)),
                ('strategy', models.CharField(choices=[('round_robin', 'Round robin'), ('fixed', 'Fixed')], default='round_robin', max_length=20)),
                ('member_ids', models.JSONField(blank=True, default=list)),
                ('rr_index', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
