# Generated by Django 6.1 on 2026-08-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_holiday_task_category_task_frequency_and_more'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspace.group'),
        ),
    ]
