# Generated by Django 6.1 on 2026-08-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_seed_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
