# Generated by Django 6.1 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_task_parent_taskactivity_kind_taskchecklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrule',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Support'), ('development', 'Developer Team'), ('hr', 'Human Resources'), ('management', 'Management')], default='', max_length=20),
        ),
    ]
