# Generated by Django 6.1 on 2026-08-29 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_warehouse_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('accounts', 'Accounts'), ('support', 'IT Team'), ('development', 'Developer Team'), ('warehouse', 'Warehouse'), ('hr', 'Human Resources'), ('management', 'Management')], default='', max_length=20),
        ),
    ]
