# Generated by Django 6.1 on 2026-08-31 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_taskcategory_pending_taskcategory_requested_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklistitem',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticked_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
