# Generated by Django 6.1 on 2026-08-17 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised')], default='draft', max_length=10)),
                ('working_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('working_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('payable_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lwp_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('earned_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('given_on', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('recovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL)),
                ('recovered_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_advances', to='payroll.payslip')),
            ],
            options={
                'ordering': ['-given_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. PF is computed on this when set, else on gross.', max_digits=10, null=True)),
                ('pf_percent', models.DecimalField(decimal_places=2, default=0, help_text='Employee PF share, e.g. 12.00. 0 = no PF.', max_digits=5)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uniq_payroll_month'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'user'), name='uniq_payslip_per_run'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('user', 'effective_from'), name='uniq_salary_effective_date'),
        ),
    ]
